# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "ddankel"
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
